name: Sync staging -> main (sin workflows) a Repo B

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A (staging)
        uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0

      - name: Push a Repo B sin .github/workflows
        env:
          TOKEN: ${{ secrets.GCCONTRACTS_MIRROR_STAGING_SECRET }}
        run: |
          set -e

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # 1) Quitar el header del GITHUB_TOKEN (evita usar github-actions[bot])
          git config --unset-all http.https://github.com/.extraheader || true
          git config --global --unset-all http.https://github.com/.extraheader || true
          sudo git config --system --unset-all http.https://github.com/.extraheader || true

          # 2) Crear un commit temporal SIN workflows (no se empuja a Repo A)
          # if [ -d ".github/workflows" ]; then
          #   rm -rf .github/workflows
          #   git add -A
          #   # solo commitea si hubo cambios
          #   if ! git diff --cached --quiet; then
          #     git commit -m "chore(sync): strip .github/workflows for mirror to Repo B"
          #   fi
          # fi


          MSG_FILE="$(mktemp)"
          git log -1 --pretty=%B > "$MSG_FILE"
          ORIG_AUTHOR="$(git log -1 --format='%an <%ae>')"
          ORIG_DATE="$(git log -1 --format='%ad' --date=iso-strict)"

          # Quitar .github completo del árbol para el mirror a Repo B
          if [ -d ".github" ]; then
            rm -rf .github
            git add -A
            # Commit temporal SOLO si hubo cambios
            if ! git diff --cached --quiet; then
              git commit --author="$ORIG_AUTHOR" --date="$ORIG_DATE" -F "$MSG_FILE"
            fi
          fi

          # 3) Agregar remoto destino con PAT
          git remote remove mirror 2>/dev/null || true
          git remote add mirror "https://x-access-token:${TOKEN}@github.com/fhidalgoGC/testbranch.git"

          # 4) (opcional) probar acceso
          git ls-remote mirror -h

          # 5) Forzar push del HEAD actual -> main en Repo B
          # git push mirror HEAD:main --force
          git push --force-with-lease mirror HEAD:main
