name: Force sync staging -> main in Repo B

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A (staging)
        uses: actions/checkout@v4
        with:
          ref: staging       # 👈 asegura que se baje la rama staging
          fetch-depth: 0     # historial completo, por si se requiere

      - name: Force push staging -> main in Repo B
        env:
          TOKEN: ${{ secrets.GCCONTRACTS_MIRROR_STAGING_SECRET }}
        run: |
          set -e
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # 🔑 quitar el header automático de checkout (usa GITHUB_TOKEN)
          git config --global --unset-all http.https://github.com/.extraheader || true

          # agregar remoto destino con tu PAT
          git remote add mirror "https://x-access-token:${TOKEN}@github.com/fhidalgoGC/testbranch.git"

          # empujar staging (HEAD actual) a main en Repo B, forzando
          git push mirror HEAD:main --force
