name: Force sync staging -> main in Repo B

on:
  push:
    branches: [staging]
  workflow_dispatch:   # 👈 habilita botón Run workflow en Actions

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A (staging)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Force push staging -> main in Repo B
        env:
          TOKEN: ${{ secrets.GCCONTRACTS_MIRROR_STAGING_SECRET }}
        run: |
          set -e
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      
          # 🔑 Quitar el header de auth que mete checkout (en TODOS los scopes)
          git config --unset-all http.https://github.com/.extraheader || true
          git config --global --unset-all http.https://github.com/.extraheader || true
          sudo git config --system --unset-all http.https://github.com/.extraheader || true
      
          # (Opcional) verifica que ya no haya extraheader
          git config --get-all http.https://github.com/.extraheader || true
      
          # Agregar remoto destino con tu PAT
          git remote remove mirror 2>/dev/null || true
          git remote add mirror "https://x-access-token:${TOKEN}@github.com/fhidalgoGC/testbranch.git"
          git remote -v
      
          # (Opcional) probar credenciales antes del push
          git ls-remote mirror -h
      
          # Empujar HEAD (staging) -> main en Repo B, forzando
          git push mirror HEAD:main --force


