name: Force sync staging -> main in Repo B

on:
  push:
    branches: [staging]
  workflow_dispatch:   # 👈 habilita botón Run workflow en Actions

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A (staging)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Force push staging -> main in Repo B
        env:
          TOKEN: ${{ secrets.GCCONTRACTS_MIRROR_STAGING_SECRET }}
        run: |
          set -e
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # 🔑 Quitar el header que pone checkout (usa GITHUB_TOKEN)
          git config --global --unset-all http.https://github.com/.extraheader || true

          # Asegurar rama staging local
          git fetch origin staging:staging

          # Agregar remoto con tu PAT
          git remote add mirror "https://x-access-token:${TOKEN}@github.com/fhidalgoGC/testbranch.git"

          # Forzar push staging -> main
          git push mirror staging:main --force

